### ISSUE TITLE
Can't manage to get short trading working

### ISSUE THREAD

**Issue by MikeKa** [EasyAI/Simple-Binance-Trader#14]
Hi! I'm trying to setup short trading here. I added indicators in trader_configuration both for short entry and short exit. But doesn't work properly. As I got, it confuses BUY and SELL side somewhere in condition checking.
The question - did you test algo for SHORT side? Is it any working example of the setup? Will appreciate any hint.

**Comment by EasyAI** [comment]
Hello, Sorry for the late response.

Can you confirm that the trader works for you in normal buy/sells for spot trading?
And confirm that margin is enabled on your account and api key has permissions for this?

**Comment by MikeKa** [comment]
Hi! I'm running in test mode. Buy/sell spot works good. Margin in the config is set on. Should I activate margin at Binance for test mode trading also?

**Comment by EasyAI** [comment]
Oh if you are running in test mode it should work fine as long as margin is also set in the settings file, what is the issue? it does not place short orders?

**Comment by EasyAI** [comment]
Added example in newest update, will close this
