### ISSUE TITLE
Webui is empty

### ISSUE THREAD

**Issue by dsiens** [EasyAI/Simple-Binance-Trader#5]
Hello,
The webui in empty, no informations about the currents trades. Just the page title is displayed.
Linux/Firefox

**Comment by dsiens** [comment]
Hello,
resolved, need to install python-socketio version prior to 5
pip3 install "python-socketio<5"

**Comment by EasyAI** [comment]
Thank you for raising this, I will see in a future version about setting the trader up to use new socket versions.
