### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by dsiens** [EasyAI/Simple-Binance-Trader#8]
Hello, here a few suggestions for next version :
- BNB autobuy if balance is empty  (or < 0.01 BNB)
- USDT (USDT-ETH,...) pairs trading. Work in test mode, but outcome in log is not accurate. Not yet tested in real mode, don't know if USDT trades will be executed.
- full balance (BTC or USDT) trade (but for one pair at a time of course), to get exponential outcome.
Thanks for the job

**Comment by EasyAI** [comment]
Hello @dsiens,
Thank you for the suggestions I will see about adding some if not all of the above features if possible.

**Comment by EasyAI** [comment]
Should be added now
