### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by TechnologyClassroom** [EasyAI/Simple-Binance-Trader#9]
I see you have no LICENSE file for this project. The default is copyright.

I would suggest releasing the code under the GPL-3.0-or-later or AGPL-3.0-or-later license so that others are encouraged to contribute changes back to your project.

**Comment by EasyAI** [comment]
Do you have any docs I can read over for this? I've never looked into it

**Comment by TechnologyClassroom** [comment]
The GPL licenses are popular examples of [copyleft](https://www.gnu.org/copyleft/) licenses that try to ensure the software will include the [four essential freedoms](https://www.gnu.org/philosophy/free-sw.en.html) if the code is forked.

**Comment by kemaltk19** [comment]
from core import botCore ??

ModuleNotFoundError: No module named 'binance_api'  ??  error

**Comment by MikeKa** [comment]
Just mention a license reference as recommended to fix any legal issues.

**Comment by EasyAI** [comment]
added under LICENSE
